[mypy]
python_version = 3.7

[pytest]
testpaths = "tests"

[tool.black]
line-length = 88
target_version = ["py37"]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_third_party = ["func_argparse"]
